---
kind: pipeline
type: docker
name: default

volumes:
  - name: cache
    host:
      path: /tmp/cache-ansible-role-drone

steps:
  - name: restore-cache-with-filesystem
    image: meltwater/drone-cache:dev
    pull: true
    settings:
      backend: "filesystem"
      restore: true
      cache_key: '{{ .Repo.Name }}_{{ checksum "requirements.txt" }}'
      archive_format: "gzip"
      mount:
        - '.venv'
    volumes:
      - name: cache
        path: /tmp/cache

  - name: install-dependencies
    image: python:3.8
    commands:
      # If the venv dir is not cached create it
      - '[ ! -d ".venv" ] && python -m venv .venv'
      - . .venv/bin/activate
      - pip install -r requirements.txt

  - name: test
    image: python:3.8
    environment:
      CF_API_KEY:
        from_secret: CF_API_KEY
      CF_API_EMAIL:
        from_secret: CF_API_EMAIL
      GITLAB_CLIENT_ID:
        from_secret: GITLAB_CLIENT_ID
      GITLAB_CLIENT_SECRET:
        from_secret: GITLAB_CLIENT_SECRET
      DO_API_TOKEN:
        from_secret: DO_API_TOKEN
      USER: root
      ANSIBLE_FORCE_COLOR: '1'
    commands:
      - . .venv/bin/activate
      - ln -s $PWD /drone/ansible-role-drone
      - molecule test
      - black --check .
      - isort --check-only .

  - name: rebuild-cache-with-filesystem
    image: meltwater/drone-cache:dev
    pull: true
    settings:
      backend: "filesystem"
      rebuild: true
      cache_key: '{{ .Repo.Name }}_{{ checksum "requirements.txt" }}'
      archive_format: "gzip"
      mount:
        - '.venv'
    volumes:
    - name: cache
      path: /tmp/cache

  - name: fail-on-debug-instruction
    image: alpine
    commands:
      - grep '|| sleep' .drone.yml || exit 1

