---
- name: Get infos on network
  docker_network_info:
    name: '{{ item.name }}'
  register: docker_network_result

- name: Start docker network
  when: not docker_network_result.exists
  docker_network:
    name: '{{ item.name }}'
