---
- assert:
    that:
      - drone_env is defined

- include_tasks: ./install_dependencies.yml

- name: Deploy web
  register: start_drone_container
  docker_container:
    comparisons:
      '*': strict
    image: '{{ drone_web_image }}'
    name: '{{ drone_web_container_name }}'
    restart_policy: unless-stopped
    memory: '{{ drone_web_memory }}'
    cpu_shares: '{{ drone_web_cpu }}'
    networks: '{{ drone_web_docker_networks|default(omit) }}'
    env: '{{ drone_env }}'
    ports: '{{ drone_web_ports }}'
    volumes:
      - '{{ drone_data_dir }}:/data'

- name: Wait for Drone to start
  register: health_check_result
  shell: >-
    docker run --net=container:{{ drone_web_container_name }}
    alpine/httpie --check-status http://{{ drone_web_container_name }}/healthz
  retries: 30
  delay: 1
  until: health_check_result.rc == 0
