---
- include_tasks: ./install_dependencies.yml

- set_fact:
    # yamllint disable-line rule:line-length
    drone_web_container: '{{ drone_web_container_defaults | combine(drone_web_container) }}'

- name: Deploy web
  register: start_drone_container
  # yamllint disable-line rule:line-length
  docker_container: '{{ drone_web_container }}'
