---
- include_tasks: ./install_dependencies.yml

- set_fact:
  # yamllint disable-line rule:line-length
    drone_worker_container: '{{ drone_worker_container_defaults | combine(drone_worker_container) }}'

- name: Deploy worker
  docker_container: '{{ drone_worker_container }}'
  register: drone_worker
