---
- include_tasks: ./install_dependencies.yml

- set_fact:
  # yamllint disable-line rule:line-length
    drone_worker_container: '{{ drone_worker_container_defaults | combine(drone_worker_container) }}'

- name: Deploy worker
  docker_container: '{{ drone_worker_container }}'
  register: drone_worker

- name: Wait for Drone to start
  register: health_check_result
  # yamllint disable rule:line-length
  shell: >-
    docker exec -it {{ drone_worker_container.name }} sh -c
    'apk add --no-cache httpie && http localhost$DRONE_HTTP_BIND/healthz --check-status --timeout=3'
  retries: 10
  delay: 1
  until: health_check_result.rc == 0
