---
- name: Deploy web
  hosts: drone_web
  tasks:
    - name: Install drone web
      include_role:
        name: ansible-role-drone
        tasks_from: server.yml
      vars:
        drone_env:
          DRONE_SERVER_HOST: drone.ipdop.com
          DRONE_SERVER_PORT: ':80'
          DRONE_SERVER_PROTO: http
          DRONE_GITLAB_CLIENT_ID: '{{ lookup("env", "GITLAB_CLIENT_ID") }}'
          DRONE_GITLAB_CLIENT_SECRET: '{{ lookup("env", "GITLAB_CLIENT_SECRET") }}'
          DRONE_RPC_HOST: drone.ipdop.com
          DRONE_RPC_PROTO: http
          DRONE_RPC_SECRET: very-secret

- name: Deploy worker
  hosts: drone_worker
  tasks:
    - name: Install drone worker
      include_role:
        name: ansible-role-drone
        tasks_from: worker.yml
      vars:
        drone_env:
          DRONE_RPC_HOST: drone.ipdop.com
          DRONE_RPC_PROTO: http
          DRONE_RPC_SECRET: very-secret
          DRONE_RUNNER_CAPACITY: '1'
          DRONE_RUNNER_NAME: runner-1
