---
# yamllint disable rule:line-length
- name: Deploy web
  hosts: drone_web
  tasks:
    - name: Install drone web
      import_role:
        name: ansible-role-drone
        tasks_from: server.yml
      vars:
        ansible_become: true
        drone_web_data_dir: /opt/foo
        drone_web_container:
          env:
            DRONE_SERVER_HOST: drone-testing-molecule.ipdop.com
            DRONE_SERVER_PORT: ':9999'
            DRONE_SERVER_PROTO: http
            DRONE_GITLAB_CLIENT_ID: 'client'
            DRONE_GITLAB_CLIENT_SECRET: 'secret'
            DRONE_RPC_HOST: '{{ ansible_all_ipv4_addresses | ipaddr("172.31.0.0/16") | max }}'
            DRONE_RPC_PROTO: http
            DRONE_RPC_SECRET: very-secret

- name: Deploy worker
  hosts: drone_worker
  tasks:
    - name: Gather facts drone web
      ansible.builtin.setup:
      delegate_to: drone_web
      delegate_facts: true

    - name: Install drone worker
      import_role:
        name: ansible-role-drone
        tasks_from: worker.yml
      vars:
        ansible_become: true
        drone_worker_container:
          env:
            DRONE_RPC_HOST: '{{ hostvars["drone_web"].ansible_all_ipv4_addresses | ipaddr("172.31.0.0/16") | max }}'
            DRONE_RPC_PROTO: http
            DRONE_RPC_SECRET: very-secret
            DRONE_RUNNER_CAPACITY: '1'
            DRONE_RUNNER_NAME: runner-1
            DRONE_HTTP_BIND: ':14000'
