---
dependency:
  name: galaxy
driver:
  name: digitalocean
platforms:
  - name: drone-web
    region: fra1
    size: 2gb
    image: docker-20-04
    groups: [drone_web]
  - name: drone-worker
    region: fra1
    size: 2gb
    image: docker-20-04
    groups: [drone_worker]
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
      host_key_checking: false
      pipelining: true

  inventory:
    group_vars:
      consul:
verifier:
  name: testinfra
  directory: ../../tests
scenario:
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - side_effect
    - verify
    - cleanup
    - destroy
