---
dependency:
  name: galaxy
driver:
  name: ec2
platforms:
  - &common
    name: drone_web
    vpc_subnet_id: subnet-1efffb7b
    image: ami-0c48db26521ca9f07
    instance_type: m5.xlarge
  - <<: *common
    name: drone_worker
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
      host_key_checking: false
      pipelining: true
verifier:
  name: testinfra
  directory: ../../tests
scenario:
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - converge
    - side_effect
    - verify
    - cleanup
    - destroy
