---
dependency:
  name: galaxy
driver:
  name: digitalocean
platforms:
  - name: drone-web
    region: fra1
    size: 2gb
    image: ubuntu-20-04-x64
    groups: [drone_web]
  - name: drone-worker
    region: fra1
    size: 2gb
    image: ubuntu-20-04-x64
    groups: [drone_worker]
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
      host_key_checking: false
      pipelining: true

  inventory:
    group_vars:
      consul:
verifier:
  name: testinfra
  directory: ../../tests
